--- #Creating an EC2 Instance in Custom VPC
       # 1>Creating a custom Security Group
       # 2>Spinning an EC2 Instance
       
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Creating a Custom Security Group
    ec2_group:
        name: newgrp
        description: sec group for allowing traffic on ports 22 and 80 and 443
        vpc_id: vpc-37cf7e4e
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0
  - name: Spinning an EC2 Instance
    ec2:
        key_name: key
        region: us-west-2
        instance_type: t2.micro
        image: ami-f2d3638a
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-5ed13b27
        assign_public_ip: yes
        group: newgrp
    register: ec2_out
  - debug: var=ec2_out
    
  
  
