---
- hosts: remote1
  connection: ssh
  remote_user: ec2-user
  sudo: yes
  gather_facts: yes
  tasks:
  - name: Create an EBS Volume
    ec2_vol:
    instance: 'i-027e1d3e9121f021a'
    volume_size: 1
    device_name: /dev/xvdf7
    volume_type: gp2
