--- #Creating an EC2 Instance in Custom VPC
       # 1>Creating a custom Security Group
       # 2>Spinning an EC2 Instance
       
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Creating a  Security Group
    ec2_group:
        name: newgrp
        description: sec group for allowing traffic on ports 22 and 80 and 443
        vpc_id: vpc-a17e41c7
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0
  - name: Spinning an EC2 Instance
    ec2:
        key_name: key
        region: us-west-2
        instance_type: t2.micro
        image: ami-223f945a
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-e33c7a85
        assign_public_ip: yes
        group: newgrp
    register: ec2_out
  - debug: var=ec2_out
  #- name: Get Ec2 Instance id
   # ec2_instance_facts:
   # register: insid
  #- debug: var=insid
  - name: Create an EBS Volume
    ec2_vol:
     instance: "{{ item.id }}"
     volume_size: 1
     device_name: /dev/xvdf7
     volume_type: gp2
    with_items: "{{ ec2_out.instances }}" 
  
