--- #Creating an EC2 Instance in Custom VPC
       # 1>Creating a custom Security Group
       # 2>Spinning an EC2 Instance
       # 3>Creating and Attaching an additional EBS volume[For attaching an EBS volume,EC2 instance should be running,so added a Wait for SSH Step.
       
       
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Creating a  Security Group
    ec2_group:
        name: newgrp
        description: sec group for allowing traffic on ports 22 and 80 and 443
        vpc_id: vpc-a17e41c7
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0
  - name: Spinning an EC2 Instance
    ec2:
        key_name: key
        region: us-west-2
        instance_type: t2.micro
        image: ami-223f945a
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-e33c7a85
        assign_public_ip: yes
        group: newgrp
    register: ec2_out
  - debug: var=ec2_out
  - name: Getting EC2 facts
    ec2_instance_facts:
    register: facts
  - debug: var=facts
  - name: Getting EC2 Metadata
    ec2_metadata_facts:
    register: metadata
  - debug: var=metadata
  - name:  Wait for SSH to come up in the newly created EC2 Instances
    wait_for: 
        host: "{{ item.private_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
    with_items: "{{ ec2_out.instances }}"
  - name: Create an EBS Volume
    ec2_vol:
     instance: "{{ item.id }}"
     region: us-west-2
     volume_size: 1
     device_name: /dev/xvdf
     volume_type: gp2
    with_items: "{{ ec2_out.instances }}" 
  
