--- #Creating an EC2 Instance in Custom VPC
       # 1>Creating a custom Security Group
       # 2>Spinning an EC2 Instance
       # 3>Adding the newly created EC2 to the hosts file
       # 4>SSH into the new EC2 and install HTTPD
       
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Creating a  Security Group
    ec2_group:
        name: newgrp
        description: sec group for allowing traffic on ports 22 and 80 and 443
        vpc_id: vpc-a17e41c7
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0
  - name: Spinning an EC2 Instance
    ec2:
        key_name: key
        region: us-west-2
        instance_type: t2.micro
        image: ami-223f945a
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-e33c7a85
        assign_public_ip: yes
        group: newgrp
    register: ec2_out
  - debug: var=ec2_out
  - name: Add the new EC2 Instance Private IP to the group
    add_host: 
     hostname: "{{ item.private_ip }}"
     groupname: node
    with_items: "{{ ec2_out.instances }}"
  - name: Wait for SSH to come up in the newly created EC2 Instance
    wait_for: 
     host: "{{ item.private_ip }}"
     port: 22
     state: started
    with_items: "{{ ec2_out.instances }}"
- hosts: node
  connection: ssh
  user: ec2-user
  sudo: yes
  gather_facts: yes
  tasks: 
  - name: Install HTTPD in the newly created EC2 Instance
    yum: pkg=httpd state=latest
  - name: Start hTTPD
    service: name=httpd state=started
    register: htt
  - debug: var=htt
  - name: copy index.html file from my Ansible Server to EC2 Instance 
    copy: src=/etc/ansible/index.html  dest=/var/www/html/index.html
 
  
