---
- hosts: "{{ any }}"
  connection: ssh
  user: ec2-user
  sudo: yes
  gather_facts: yes
  tasks: 
  - name: Install HTTPD
    yum: pkg=httpd state=absent
    tags: 
      - httpdtag
  - name: Install TELNET
    yum: pkg=telnet state=absent
    tags: 
      - telnettag
  - name: Install LYNX
    yum: pkg=lynx state=latest
    tags: 
       - lynxtag
