---
- hosts: "{{ any }}"
  connection: ssh
  user: ec2-user
  sudo: yes
  gather_facts: yes
  tasks: 
  - name: Install HTTPD
    yum: pkg=httpd state=absent
    tags: 
      - httpdtag
  - name: List all the contents
    command: ls -al 
    tags: 
       - listtag
  - name: Create a file
    command: touch file1.txt
    tags: 
       - createtag
